/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviousTripsRouteImport } from './routes/previous-trips'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripsIdResultRouteImport } from './routes/trips.$id.result'
import { Route as TripsIdPlanRouteImport } from './routes/trips.$id.plan'
import { Route as TripsIdLiveRouteImport } from './routes/trips.$id.live'

const PreviousTripsRoute = PreviousTripsRouteImport.update({
  id: '/previous-trips',
  path: '/previous-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdResultRoute = TripsIdResultRouteImport.update({
  id: '/trips/$id/result',
  path: '/trips/$id/result',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdPlanRoute = TripsIdPlanRouteImport.update({
  id: '/trips/$id/plan',
  path: '/trips/$id/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdLiveRoute = TripsIdLiveRouteImport.update({
  id: '/trips/$id/live',
  path: '/trips/$id/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/previous-trips': typeof PreviousTripsRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/$id/live': typeof TripsIdLiveRoute
  '/trips/$id/plan': typeof TripsIdPlanRoute
  '/trips/$id/result': typeof TripsIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/previous-trips': typeof PreviousTripsRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/$id/live': typeof TripsIdLiveRoute
  '/trips/$id/plan': typeof TripsIdPlanRoute
  '/trips/$id/result': typeof TripsIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/previous-trips': typeof PreviousTripsRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/$id/live': typeof TripsIdLiveRoute
  '/trips/$id/plan': typeof TripsIdPlanRoute
  '/trips/$id/result': typeof TripsIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/previous-trips'
    | '/trips/new'
    | '/trips/$id/live'
    | '/trips/$id/plan'
    | '/trips/$id/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/previous-trips'
    | '/trips/new'
    | '/trips/$id/live'
    | '/trips/$id/plan'
    | '/trips/$id/result'
  id:
    | '__root__'
    | '/'
    | '/previous-trips'
    | '/trips/new'
    | '/trips/$id/live'
    | '/trips/$id/plan'
    | '/trips/$id/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviousTripsRoute: typeof PreviousTripsRoute
  TripsNewRoute: typeof TripsNewRoute
  TripsIdLiveRoute: typeof TripsIdLiveRoute
  TripsIdPlanRoute: typeof TripsIdPlanRoute
  TripsIdResultRoute: typeof TripsIdResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/previous-trips': {
      id: '/previous-trips'
      path: '/previous-trips'
      fullPath: '/previous-trips'
      preLoaderRoute: typeof PreviousTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id/result': {
      id: '/trips/$id/result'
      path: '/trips/$id/result'
      fullPath: '/trips/$id/result'
      preLoaderRoute: typeof TripsIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id/plan': {
      id: '/trips/$id/plan'
      path: '/trips/$id/plan'
      fullPath: '/trips/$id/plan'
      preLoaderRoute: typeof TripsIdPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id/live': {
      id: '/trips/$id/live'
      path: '/trips/$id/live'
      fullPath: '/trips/$id/live'
      preLoaderRoute: typeof TripsIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviousTripsRoute: PreviousTripsRoute,
  TripsNewRoute: TripsNewRoute,
  TripsIdLiveRoute: TripsIdLiveRoute,
  TripsIdPlanRoute: TripsIdPlanRoute,
  TripsIdResultRoute: TripsIdResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
